apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertagent.fullname" . }}-secrets
  namespace: {{ include "alertagent.namespace" . }}
  labels:
    {{- include "alertagent.labels" . | nindent 4 }}
type: Opaque
data:
  # 数据库配置
  database-name: {{ .Values.secrets.database.name | b64enc }}
  database-username: {{ .Values.secrets.database.username | b64enc }}
  database-password: {{ .Values.secrets.database.password | b64enc }}
  database-ssl-mode: {{ .Values.secrets.database.sslMode | b64enc }}
  
  # Redis 配置
  redis-password: {{ .Values.secrets.redis.password | b64enc }}
  redis-database: {{ .Values.secrets.redis.database | b64enc }}
  
  # JWT 配置
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc }}
  jwt-expiration: {{ .Values.secrets.jwt.expiration | b64enc }}
  
  # 加密配置
  encryption-key: {{ .Values.secrets.encryption.key | b64enc }}
  
  # SMTP 配置
  smtp-host: {{ .Values.secrets.smtp.host | b64enc }}
  smtp-port: {{ .Values.secrets.smtp.port | b64enc }}
  smtp-username: {{ .Values.secrets.smtp.username | b64enc }}
  smtp-password: {{ .Values.secrets.smtp.password | b64enc }}
  
  # 钉钉配置
  dingtalk-token: {{ .Values.secrets.dingtalk.token | b64enc }}
  dingtalk-secret: {{ .Values.secrets.dingtalk.secret | b64enc }}
  
  # Dify 配置
  dify-api-key: {{ .Values.secrets.dify.apiKey | b64enc }}
  dify-base-url: {{ .Values.secrets.dify.baseURL | b64enc }}

---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertagent.fullname" . }}-postgres-secret
  namespace: {{ include "alertagent.namespace" . }}
  labels:
    {{- include "alertagent.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  username: {{ .Values.postgresql.auth.username | b64enc }}
  database: {{ .Values.postgresql.auth.database | b64enc }}
{{- end }}

---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertagent.fullname" . }}-redis-secret
  namespace: {{ include "alertagent.namespace" . }}
  labels:
    {{- include "alertagent.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc }}
{{- end }}

---
{{- if .Values.ruleServer.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertagent.fullname" . }}-mysql-secret
  namespace: {{ include "alertagent.namespace" . }}
  labels:
    {{- include "alertagent.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.ruleServer.mysql.auth.rootPassword | b64enc }}
  mysql-password: {{ .Values.ruleServer.mysql.auth.password | b64enc }}
  mysql-user: {{ .Values.ruleServer.mysql.auth.username | b64enc }}
  mysql-database: {{ .Values.ruleServer.mysql.auth.database | b64enc }}
{{- end }}