version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: alertagent-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: alert_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - alertagent-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alert_agent"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: alertagent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alertagent-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # # Ollama AI 服务
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: alertagent-ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - alertagent-network
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
  #     timeout: 10s
  #     retries: 5
  #     start_period: 30s

  # 数据库迁移服务 (一次性运行)
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: alertagent-migrate
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: alert_agent
      LOG_LEVEL: info
    networks:
      - alertagent-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - migration
    restart: "no"

  # # 可选：pgAdmin 数据库管理工具
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: alertagent-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - alertagent-network

  # # 可选：Redis Commander Redis管理工具
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: alertagent-redis-commander
  #   restart: unless-stopped
  #   environment:
  #     REDIS_HOSTS: local:redis:6379
  #   ports:
  #     - "8082:8081"
  #   depends_on:
  #     - redis
  #   networks:
  #     - alertagent-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  ollama_data:
    driver: local

networks:
  alertagent-network:
    driver: bridge