apiVersion: v1
kind: ConfigMap
metadata:
  name: alertagent-config
  namespace: alertagent
  labels:
    app.kubernetes.io/name: alertagent
    app.kubernetes.io/component: config
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      mode: "release"
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
    
    database:
      host: "postgres-service"
      port: 5432
      name: "alert_agent"
      user: "postgres"
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: 300s
      ssl_mode: "disable"
    
    redis:
      host: "redis-service"
      port: 6379
      db: 0
      pool_size: 10
      min_idle_conns: 5
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
    
    logging:
      level: "info"
      format: "json"
      output: "stdout"
      file_rotation:
        enabled: false
    
    metrics:
      enabled: true
      port: 9090
      path: "/metrics"
    
    tracing:
      enabled: true
      jaeger_endpoint: "http://jaeger-collector:14268/api/traces"
      sample_rate: 0.1
    
    health:
      enabled: true
      path: "/health"
      version: "1.0.0"
    
    features:
      ai_analysis: true
      auto_resolution: false
      cluster_management: true
      notification_templates: true
    
    rate_limit:
      requests_per_minute: 100
      burst: 20
    
    cache:
      ttl: 300s
      cleanup_interval: 600s
  
  features.yaml: |
    features:
      ai_analysis:
        enabled: true
        description: "AI智能分析功能"
        rollout_percentage: 100
      
      auto_resolution:
        enabled: false
        description: "自动解决告警功能"
        rollout_percentage: 0
      
      cluster_management:
        enabled: true
        description: "集群管理功能"
        rollout_percentage: 100
      
      notification_templates:
        enabled: true
        description: "通知模板功能"
        rollout_percentage: 100
      
      advanced_analytics:
        enabled: false
        description: "高级分析功能"
        rollout_percentage: 10
        conditions:
          - user_tier: "premium"
          - region: "us-west-2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertagent-prometheus-config
  namespace: alertagent
  labels:
    app.kubernetes.io/name: alertagent
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    scrape_configs:
      - job_name: 'alertagent-api'
        static_configs:
          - targets: ['alertagent-api-service:9090']
        metrics_path: /metrics
        scrape_interval: 30s
      
      - job_name: 'alertagent-worker'
        static_configs:
          - targets: ['alertagent-worker-service:9091']
        metrics_path: /metrics
        scrape_interval: 30s
      
      - job_name: 'rule-server'
        static_configs:
          - targets: ['rule-server-service:8080']
        metrics_path: /metrics
        scrape_interval: 30s
      
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter:9187']
        scrape_interval: 30s
      
      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter:9121']
        scrape_interval: 30s
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - alertagent
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name