apiVersion: v1
kind: Namespace
metadata:
  name: alertagent
  labels:
    name: alertagent
    app.kubernetes.io/name: alertagent
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: alertagent-system
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "AlertAgent 告警管理系统命名空间"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: alertagent-quota
  namespace: alertagent
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: alertagent-limits
  namespace: alertagent
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim