server:
    port: 8080
    mode: debug
    jwt_secret: your-jwt-secret-key-change-in-production
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 60

gateway:
    rate_limit:
        enabled: true
        rps: 100
        burst: 200
    auth:
        enabled: true
        skip_paths:
            - "/api/v1/health"
            - "/api/v1/auth/login"
            - "/api/v1/auth/register"
        token_expiry: 24
        refresh_expiry: 168
    cors:
        enabled: true
        allow_origins:
            - "*"
        allow_methods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
        allow_headers:
            - "Content-Type"
            - "Authorization"
            - "X-Request-ID"
            - "X-CSRF-Token"
        expose_headers:
            - "Content-Length"
            - "X-Request-ID"
        allow_credentials: true
database:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: along123
    dbname: alert_agent
    charset: utf8mb4
    max_idle_conns: 10
    max_open_conns: 100
    parse_time: true
    loc: Local
ollama:
    enabled: true
    api_endpoint: http://10.98.65.131:11434
    model: llama3:latest
    timeout: 300
    max_retries: 3
redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
    pool_size: 100
    min_idle_conns: 10
    max_retries: 3
    dial_timeout: 5
log:
    level: debug
    filename: logs/alert_agent.log
    max_size: 100
    max_age: 7
    max_backups: 10
    compress: true
