server:
    port: 8080
    mode: debug
    jwt_secret: your-jwt-secret-key
database:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: along123
    dbname: alert_agent
    charset: utf8mb4
    max_idle_conns: 10
    max_open_conns: 100
    parse_time: true
    loc: Local
ollama:
    enabled: true
    api_endpoint: http://10.98.65.131:11434
    model: llama3:latest
    timeout: 30
    max_retries: 3
redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
    pool_size: 100
    min_idle_conns: 10
    max_retries: 3
    dial_timeout: 5
log:
    level: info
    filename: logs/alert_agent.log
    max_size: 100
    max_age: 7
    max_backups: 10
    compress: true
